branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
environment-defaults:
  node-express-env:
    branch: master
    repository: restapi-server
global:
  application_name: RestAPI_Project
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: restapi-server
  sc: git
  workspace_type: Application
