GET http://localhost:3001/coolerDate/123

###

POST http://localhost:3001/coolerdate/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode11"
}

###


POST http://localhost:3001/coolerdate/updatefirstAccessTime
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode11"
}

###


DELETE http://localhost:3001/coolerdate/deleteone
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode11"
}

###



POST http://localhost:3001/coolerdate/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode11"
}

###