GET http://localhost:3001/coolerDate/123

###

POST http://localhost:3001/coolerdate/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode11"
}

###


POST http://localhost:3001/coolerdate/updateFirstAccessTime
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode04",
}
