

POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "default",
  "content": [
    "Hi there 👋🏽, my name is Rodo. I'm also a software engineer / QUT graduate.",
    "My personalities? - I'm funny and outgoing, resourceful, creative, logical",
    "What do I like? - I like coding & technology, travelling, outdoor activities: running, hiking, Vietnamese street coffee-ing, Asian food, bubble tea, films, working-out, deep conversation, animals and plants, reading books.",
    "What do I like to do with my girlfriend besides what I already like? - Spending quality time together of course, watching films in bed, hugging and cuddling, lying under the sky, travelling, hiking, being alone together, massaging my girlfriend, (I also don't mind) kissing in public.",
    "How am I like? - I'm 1.7m, 60kg, Asian born and raised, introvert but also extremely extrovert with the right people.",
    "Feel free to view other things in my website, you can alway comeback here with the exact link."
  ]
}

###

POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "job",
  "content": [
    "Hi 👋🏽, my name is Rodo.",
    "If you're seeing this, that means I want to join your company as a software engineer! This is just a walkthrough of my application, you can read the rest in my resume (rodonguyen.dev/resume)",
    "So, this is CoolerDate: A unique full-stack app built to make “Asking someone out for a date” simpler and even more special.",
    "Each user can create a customised & exclusive code to give to any person, who you're attracted to, to ask them out. If they agree, they will fill the form below with their info and their response will appear in the MongoDB soon enough. Simple as that.",
    "I applied MERN architecture (MongoDB, ExpressJS, React, NodeJS), designed suitable database schemas, implemented multi-step forms and a multitude of API endpoints, and utilised React Hooks (e.g., useMemo), all of which have broadened my experience in Full-stack development, System Design, and Database Modeling. Furthermore, I fully automated server testing process using Chai framework due to high level of complexity.",
    "View its codebase here: https://github.com/rodonguyen/CoolerDate"
  ]
}

###


POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "p1",
  "content": ["p1", "p2", "p3?"]
}

###
  # "content": "<p>Who am I? I'm Rodo, a software engineer, QUT graduate.</p>
  #       <p>
  #         What do I like? I like coding & technology, travelling, outdoor
  #         activities: running, hiking, Vietnamese street coffee-ing, Asian food,
  #         working-out, deep conversation, animals and plants, reading books, and
  #         females.
  #       </p>
  #       <p>
  #         How am I like? I'm 1.7m, 60kg, Asian born and raised, 5.5+in,
  #         introvert. I'm trying to gain some weights though.
  #       </p>
  #       <p>
  #         About what I do, check{\" \"}
  #         <a href=\"/\" target=\"_blank\" rel=\"noopener noreferrer\">
  #           the main page
  #         </a>{\" \"}
  #         and you can alway comeback here later with the exact link.
  #       </p>"
###


DELETE http://localhost:3001/coolerdate/profile/deleteOne
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "p1"
}

###



POST http://localhost:3001/coolerdate/profile/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "goodboy"
}


###

POST http://localhost:3001/coolerdate/profile/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "neutral"
}

###