

POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "neutral",
  "content": [
    "Hi there 👋🏽, my name is Rodo. I'm also a software engineer / QUT graduate.",
    "My personalities? - I'm funny and outgoing, resourceful, creative, logical",
    "What do I like? - I like coding & technology, travelling, outdoor activities: running, hiking, Vietnamese street coffee-ing, Asian food, bubble tea, films, working-out, deep conversation, animals and plants, reading books.",
    "What do I like to do with my girlfriend besides what I already like? - Spending quality time together of course, being alone together, watching films in bed, hugging and cuddling, lying under the sky, travelling, hiking, massaging my girlfriend, (I also don't mind) kissing in public.",
    "How am I like? - I'm 1.7m, 60kg, Asian born and raised, 5.5+in, introvert but also depending on who I'm talking to",
    "Feel free to view other things in my website, you can alway comeback here with the exact link."
  ]
}

###

POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "goodboy99999",
  "content": [
    "Who am I? I'm Rodo. I'm also a software engineer / QUT graduate.",
    "What do I like? I like coding & technology, travelling, outdoor activities: running, hiking, Vietnamese street coffee-ing, Asian food, working-out, deep conversation, animals and plants, reading books.",
    "How am I like? I'm 1.7m, 60kg, Asian born and raised, 5.5+in, quite introvert.",
    "Feel free to view other stuff in my website and you can alway comeback here later with the exact link."
  ]
}

###


POST http://localhost:3001/coolerdate/profile/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "p1",
  "content": ["p1", "p2", "p3?"]
}

###
  # "content": "<p>Who am I? I'm Rodo, a software engineer, QUT graduate.</p>
  #       <p>
  #         What do I like? I like coding & technology, travelling, outdoor
  #         activities: running, hiking, Vietnamese street coffee-ing, Asian food,
  #         working-out, deep conversation, animals and plants, reading books, and
  #         females.
  #       </p>
  #       <p>
  #         How am I like? I'm 1.7m, 60kg, Asian born and raised, 5.5+in,
  #         introvert. I'm trying to gain some weights though.
  #       </p>
  #       <p>
  #         About what I do, check{\" \"}
  #         <a href=\"/\" target=\"_blank\" rel=\"noopener noreferrer\">
  #           the main page
  #         </a>{\" \"}
  #         and you can alway comeback here later with the exact link.
  #       </p>"
###


DELETE http://localhost:3001/coolerdate/profile/deleteOne
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "p1"
}

###



POST http://localhost:3001/coolerdate/profile/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "goodboy"
}


###

POST http://localhost:3001/coolerdate/profile/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "profile": "neutral"
}

###