
GET http://localhost:3001/hi

###

POST http://localhost:3001/coolerdate/code/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "hireme",
  "profile": "job"
}


###

POST http://localhost:3001/coolerdate/code/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "c5"
}


###

POST http://localhost:3001/coolerdate/code/check
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "c1"
}

###


PATCH http://localhost:3001/coolerdate/code/addFirstAccessTime
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode12"
}
###


PATCH http://localhost:3001/coolerdate/code/nullifyFirstAccessTime
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode12"
}

###


DELETE http://localhost:3001/coolerdate/code/deleteone
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "beach"
}

###


DELETE http://localhost:3001/coolerdate/code/deleteone
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "n4"
}

###



POST http://localhost:3001/coolerdate/code/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode83"
}

###