
GET http://localhost:3001/hi

###

POST http://localhost:3001/coolerdate/code/add
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode123",
  "profileCode": "badboy"
}

###


PATCH http://localhost:3001/coolerdate/code/patchFirstAccessTime
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode99101"
}

###


DELETE http://localhost:3001/coolerdate/code/deleteone
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode123"
}

###



POST http://localhost:3001/coolerdate/code/find
Content-Type: application/json

{
  "username": "rodonguyen",
  "code": "newcode999"
}

###